import Login from "@/components/Login";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Login/>
    </div>
  );
}
